config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'pagination/change'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  mount Peek::Railtie => '/peek'

  get 'welcome/index'

  root 'welcome#index'

  concern :commentable do
    resources :comments, shallow: true do
      member do
        get 'reply', to: 'comments#new_reply'
        post 'reply', to: 'comments#create_reply'
      end
    end
  end

  resources :tags do
    member do
      put 'approve', to: 'tags#approve'
      put 'disapprove', to: 'tags#disapprove'
    end
  end

  resources :marks, only: [:create, :destroy]
  post 'marks/:mark_type/handle', to: 'marks#handle'

  resources :articles, except: :index, concerns: [:commentable]

  resources :blogs do
    resources :articles, only: :index
  end

  get 'users/profile', as: 'user_root'
  get 'users/:user_id/profile', to: 'users#profile'

  get 'user/edit', to: 'users#edit'

  post 'pagination/change', to: 'pagination#change'

  post 'trumbowig/file-upload', to: 'trumbowyg/trumbowyg#file_upload'

  devise_for :users, controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  devise_scope :user do
    post 'profile/image', to: 'registrations#profile_image_upload'
  end
end

app/models/blog.rb
include ApplicationHelper

class Blog < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  belongs_to :user

  before_save do
    self.description = sanitize_content(self.description)
  end

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find params[:id]
    @articles = @blog.articles.page(params[:page])
  end

  def new
    if can? :create, Blog
      @blog = Blog.new
    else
      raise CanCan::AccessDenied.new('You are not permitted to create blogs!', :create, Blog)
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    unless can? :edit, @blog
      raise CanCan::AccessDenied.new('You are not permitted to update this blog!', :create, Blog)
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if can? :update, @blog
      if @blog.update(blog_params)
        redirect_to @blog
      else
        render 'edit'
      end
    else
      raise CanCan::AccessDenied.new('You are not permitted to update this blog!', :create, Blog)
    end
  end

  def create
    if can? :create, Blog
      @blog = Blog.new blog_params
      @blog.user = current_user

      if @blog.save
        redirect_to @blog
      else
        render 'new'
      end
    else
      raise CanCan::AccessDenied.new('You are not permitted to create blogs!', :create, Blog)
    end
  end

  def destroy
    @blog = Blog.find(params[:id])

    if can? :destroy, @blog
      @blog.destroy
    else
      raise CanCan::AccessDenied.new('You are not permitted to destroy this blog!', :destroy, @blog)
    end

    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.haml
.blog.entity
  %h3= link_to_unless_current blog.title, blog if defined? show_title and show_title
  %p= blog.user.email
  %p.description.field-text
    - text = (defined? truncate_length) ? HTML_Truncator.truncate(blog.description, truncate_length) : blog.description
    = raw text
  - links = []
  - links.push(link_to_unless_current('back', blogs_path, title: 'Back to the blogs list') {})
  - links.push(link_to 'create new article', new_article_path(blog_id: blog.id), title: 'Click to add new article to this blog') if can? :update, blog
  = render partial: 'application/action_links', locals: {object: blog, links: links}

app/views/blogs/_form.html.haml
= form_for @blog do |f|
  = render partial: 'validation_errors', locals: {errors: @blog.errors}
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.trumbowyg_area :description
  = f.submit nil, class: 'pull-right'

app/views/blogs/edit.html.haml
= page_h1 "Edit blog #{@blog.title}"

.row
  = render 'form'
  = link_to 'back', blog_path, title: "Back to the #{@blog.title}"

app/views/blogs/index.html.haml
- @blogs.each do |blog|
  .row
    = render partial: blog, object: blog, locals: {show_title: true, truncate_length: 50}

app/views/blogs/new.html.haml
= page_h1 'New blog'

.row
  = render 'form'
  = link_to 'back', blogs_path, title: 'Back to the blogs list'

app/views/blogs/show.html.haml
= page_h1 @blog.title

= render 'blogs/blog', blog: @blog, show_title: false

= render 'articles/blog_articles', blog: @blog, articles: @articles