config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'pagination/change'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  mount Peek::Railtie => '/peek'

  get 'welcome/index'

  root 'welcome#index'

  concern :commentable do
    resources :comments, shallow: true do
      member do
        get 'reply', to: 'comments#new_reply'
        post 'reply', to: 'comments#create_reply'
      end
    end
  end

  resources :tags do
    member do
      put 'approve', to: 'tags#approve'
      put 'disapprove', to: 'tags#disapprove'
    end
  end

  resources :marks, only: [:create, :destroy]
  post 'marks/:mark_type/handle', to: 'marks#handle'

  resources :articles, except: :index, concerns: [:commentable]

  resources :blogs do
    resources :articles, only: :index
  end

  get 'users/profile', as: 'user_root'
  get 'users/:user_id/profile', to: 'users#profile'

  get 'user/edit', to: 'users#edit'

  post 'pagination/change', to: 'pagination#change'

  post 'trumbowig/file-upload', to: 'trumbowyg/trumbowyg#file_upload'

  devise_for :users, controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  devise_scope :user do
    post 'profile/image', to: 'registrations#profile_image_upload'
  end
end

app/models/article.rb
include ApplicationHelper

class Article < ActiveRecord::Base
  belongs_to :blog
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :marks, as: :markable, dependent: :destroy
  has_many :tags_associations, as: :taggable, dependent: :destroy
  has_many :tags, through: :tags_associations

  mount_uploader :image, ArticleImageUploader

  paginates_per 3

  before_save do
    self.text = sanitize_content(self.text)
  end

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @blog = Blog.find(params[:blog_id])
    @articles = @blog.articles.page params[:page]
  end

  def show
    @article = Article.find params[:id]
    @comments = @article.comments.page(params[:page])
  end

  def new
    if can? :create, Article
      @user_blogs = editable_blogs

      raise 'You have no blogs!' if @user_blogs.blank?

      @article = Article.new
    else
      raise CanCan::AccessDenied.new('You are not permitted to create articles!', :create, Article)
    end

    if params.include? :blog_id
      @blog = Blog.find params[:blog_id]
      if cannot? :update, @blog
        raise CanCan::AccessDenied.new('You are not permitted to create articles in this blog!', :create, Article)
      end

      @article.blog_id = @blog.id
    end
  end

  def create
    @blog = Blog.find(params[:article][:blog])
    if can? :update, @blog
      @article = @blog.articles.create(article_params)
      redirect_to blog_path(@blog)
    else
      raise CanCan::AccessDenied.new('You are not permitted to create articles in this blog!', :create, Article)
    end
  end

  def edit
    @article = Article.find(params[:id])
    unless can? :edit, @article
      raise CanCan::AccessDenied.new('You are not permitted to update this article!', :create, Article)
    end

    @user_blogs = editable_blogs

    raise 'You have no blogs!' if @user_blogs.blank?
  end

  def update
    @article = Article.find(params[:id])
    @article.blog = Blog.find params[:article][:blog]

    if can? :update, @article
      if @article.update(article_params)
        redirect_to @article
      else
        @user_blogs = editable_blogs

        render 'edit'
      end
    else
      raise CanCan::AccessDenied.new('You are not permitted to update this article!', :create, Article)
    end
  end

  def destroy
    @article = Article.find(params[:id])

    if can? :destroy, @article
      @article.destroy
    else
      raise CanCan::AccessDenied.new('You are not permitted to destroy this article!', :destroy, @article)
    end

    redirect_to url_for @article.blog
  end

  private
  def article_params
    # Exclude tag ids that are not allowed for current user.
    user_tags = Tag.allowed_for_user current_user
    params[:article][:tag_ids].select! do |id|
      user_tags.exists? id
    end

    params.require(:article).permit(:title, :text, :image, tag_ids: [])
  end

  def editable_blogs(user = current_user)
    if user.ability.can? :update, Blog, ['user_id != ?', user.id]
      Blog.all.select { |blog| can? :update, blog }
    else
      user.blogs
    end
  end

  def remove_image!
    @article.remove_image!
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
.article.entity.row
  - if defined? show_title and show_title
    %h3= link_to_unless_current article.title, article
  %small= render 'tags/list', tags: article.tags

  -# Article image.
  = render 'articles/article_image', article: article, wrapper_class: 'center-block'

  .description.field-text
    = raw article.text
  - links = []
  - links.push(link_to_unless_current('back', article.blog, title: "Back to the #{article.blog.title}") {})
  - links.push(link_to 'add a comment', new_article_comment_path(article), title: "Click to add a comment to #{article.title}", remote: true, format: :html, class: 'get-comment-form')
  .actions.clearfix
    = render 'application/action_links', object: article, links: links
    = render 'marks/object_marks', object: article

  .comments
    = render 'comments/comments', comments: article.comments.page(params[:page]), object: article

app/views/articles/_article_image.html.haml
- version ||= 'default'
- if article.image.present?
  .article-image.clearfix{class: "#{wrapper_class if defined? wrapper_class}"}
    - url = article.image.respond_to?(version) ? article.image.send(version).url : article.image.url
    = image_tag url, class: 'center-block'

app/views/articles/_blog_articles.html.haml
.row.articles
  - paginator_options = {controller: 'articles', action: 'index', blog_id: blog.id}
  = pagination_items articles, :ul, {html_class: %w(articles-list list-unstyled), header: ['Header']}, paginator_options do |article|
    - render 'articles/teaser', article: article

app/views/articles/_form.html.haml
= form_for @article do |f|
  = render partial: 'validation_errors', locals: {errors: @article.errors}
  .field
    - blogs_options = []
    - @user_blogs.each { |blog| blogs_options.push [blog.title, blog.id] }
    = f.label :blog
    = f.select :blog, blogs_options, selected: @article.blog_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :text
    = f.trumbowyg_area :text
  .field
    = f.label :tags
    - tags = Tag.allowed_for_user(current_user)
    - unless tags.blank?
      = f.select :tag_ids, options_from_collection_for_select(tags, :id, :title, @article.tags.map { |t| t.id }), {}, { :multiple => true, :size => 5 }
    - else
      %div
        There is no enabled tags now.
    - if can? :create, Tag
      .create-tag
        = link_to 'create tag', new_tag_path, target: :blank
  .actions
    = f.submit nil, class: 'pull-right'

app/views/articles/_teaser.html.haml
.panel.panel-default.panel-margin.article.teaser
  .panel-heading
    = link_to article.title, article_path(article), class: 'lead'
  .panel-body
    %small= render 'tags/list', tags: article.tags

    -# Article image.
    = render 'articles/article_image', article: article, wrapper_class: 'pull-left', version: 'teaser'

    = raw HTML_Truncator.truncate(article.text, 100)
  .panel-footer.clearfix
    .pull-left
      = link_to article, class: 'base-pad comments-counter' do
        %span.glyphicon.glyphicon-comment
        = article.comments.count
    = render 'marks/object_marks', object: article

app/views/articles/edit.html.haml
= page_h1 "Edit article #{@article.title}"

.row
  = render 'form'
  = link_to 'back', article_path, title: "Back to the #{@article.title}"

app/views/articles/index.js.erb
var element = "<%=j render 'articles/blog_articles', blog: @blog, articles: @articles %>";
$(document).trigger('infinite:load', element);

app/views/articles/new.html.haml
= page_h1 'New article'

.row
  = render 'form'
  - if params.include? :blog_id
    = link_to 'back', blog_path(params[:blog_id]), title: "Back to the #{@blog.title}"
  - else
    = link_to 'back', blogs_path, title: 'Back to the blogs list'

app/views/articles/show.html.haml
= page_h1 @article.title

= render @article, locals: {show_title: false}