config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'pagination/change'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  mount Peek::Railtie => '/peek'

  get 'welcome/index'

  root 'welcome#index'

  concern :commentable do
    resources :comments, shallow: true do
      member do
        get 'reply', to: 'comments#new_reply'
        post 'reply', to: 'comments#create_reply'
      end
    end
  end

  resources :tags do
    member do
      put 'approve', to: 'tags#approve'
      put 'disapprove', to: 'tags#disapprove'
    end
  end

  resources :marks, only: [:create, :destroy]
  post 'marks/:mark_type/handle', to: 'marks#handle'

  resources :articles, except: :index, concerns: [:commentable]

  resources :blogs do
    resources :articles, only: :index
  end

  get 'users/profile', as: 'user_root'
  get 'users/:user_id/profile', to: 'users#profile'

  get 'user/edit', to: 'users#edit'

  post 'pagination/change', to: 'pagination#change'

  post 'trumbowig/file-upload', to: 'trumbowyg/trumbowyg#file_upload'

  devise_for :users, controllers: {registrations: 'registrations'}, path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  devise_scope :user do
    post 'profile/image', to: 'registrations#profile_image_upload'
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tags_associations, dependent: :destroy
  has_many :taggable, through: :tags_associations, source: :taggable, source_type: 'Article'
  belongs_to :user

  # Select only approved tags (status = true) or tags that belongs to user.
  # If user can manage tags do nothing.
  def self.allowed_for_user(user)
    if user
      if user.ability.can? :manage, Tag
        all
      else
        where('user_id = :id or status = :status', id: user.id, status: true)
      end
    else
      where(status: true)
    end
  end

  def approved?
    status
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.allowed_for_user(current_user).order(:id).includes(:taggable)
  end

  def show
    @tag = Tag.find(params[:id])
    @taggables = @tag.taggable
  end

  def new
    if can? :create, Tag
      @tag = Tag.new
    else
      raise CanCan::AccessDenied.new('You are not permitted to create tags!', :create, Tag)
    end
  end

  def create
    if can? :create, Tag
      # Unauthenticated user cannot set tag status.
      params[:tag].delete :status if cannot? :update, Tag

      @tag = Tag.new tag_params
      @tag.user = current_user

      if @tag.save
        redirect_to tags_path
      else
        render 'form'
      end
    else
      raise CanCan::AccessDenied.new('You are not permitted to create tags!', :create, Tag)
    end
  end

  def edit
    if can? :update, Tag
      @tag = Tag.find params[:id]
    else
      raise CanCan::AccessDenied.new('You are not permitted to update tags!', :update, Tag)
    end
  end

  def update
    # If certain button is clicked, do appropriate action.
    if params.include? :approve
      approve
    elsif params.include? :disapprove
      disapprove
    elsif params.include? :remove
      destroy
    end

    # If params include tag element, update tag in DB.
    if params.include? :tag
      processor :update do |tag|
        tag.update tag_params
      end
    end
  end

  def approve
    processor :update do |tag|
      tag.status = true
      tag.save
    end
  end

  def disapprove
    processor :update do |tag|
      tag.status = false
      tag.save
    end
  end

  def destroy
    processor :destroy do |tag|
      tag.destroy
    end
  end

  private

  def processor(permission)
    tag = Tag.find params[:id]
    if can? permission, tag
      # Do something with tag.
      yield tag
    else
      raise CanCan::AccessDenied.new('You are not permitted to administer tags!', permission, tag)
    end

    redirect_to tags_path
  end

  def tag_params
    params.require(:tag).permit(:title, :status)
  end
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/tags/_actions_forms.html.haml
.btn-group{class: html_class}
  - if tag.approved?
    = button_to url_for(action: :disapprove, id: tag.id), method: :put, class: 'btn btn-default btn-sm' do
      .glyphicon.glyphicon-remove-sign
      Disapprove
  - else
    = button_to url_for(action: :approve, id: tag.id), method: :put, class: 'btn btn-default btn-sm' do
      .glyphicon.glyphicon-ok-sign
      Approve

  = button_to url_for(action: :edit, id: tag.id), method: :get, class: 'btn btn-default btn-sm' do
    .glyphicon.glyphicon-pencil
    Edit

  = button_to url_for(action: :destroy, id: tag.id), method: :delete, class: 'btn btn-default btn-sm' do
    .glyphicon.glyphicon-trash
    Remove

app/views/tags/_form.html.haml
= form_for tag do |f|
  .field.form-group
    = f.label :title
    = f.text_field :title
  - if can? :approve, tag
    .field.form-group
      = f.check_box :status
      = f.label :approved

  .actions
    = f.submit 'Save'

app/views/tags/_list.html.haml
- if tags.present?
  %ul.list-inline.list-unstyled.tags-list
    - tags.each do |tag|
      %li.tag
        = link_to tag_path(tag) do
          %span.glyphicon.glyphicon-tag
          = tag.title

app/views/tags/edit.html.haml
= render 'form', tag: @tag

app/views/tags/index.html.haml
- page_h1 'Tags'

.row
  - if @tags.present?
    %ul.list-group
      - @tags.each do |tag|
        %li.list-group-item.clearfix
          %a.pull-left{ href: url_for(tag)}
            %span.badge
              %span.glyphicon.glyphicon-tags
              = tag.taggable.count

            %span.title
              = tag.title

          - unless tag.approved?
            &nbsp;
            %small.text-muted
              %span.glyphicon.glyphicon-alert
              Tag is not approved yet

          - if can? :manage, Tag
            = render 'actions_forms', tag: tag, html_class: 'pull-right'
  - else
    .alert.alert-info
      There is no tags yet.
  = link_to 'create new tag', new_tag_path

app/views/tags/new.html.haml
= render 'form', tag: @tag

app/views/tags/show.html.haml
- page_h1 "#{@tag.title} tag nodes"

.row
  - if @taggables.present?
    - @taggables.each do |taggable|
      - namespace = taggable.class.to_s.downcase
      - partial = "#{namespace}s/teaser"
      = render partial, namespace.to_sym => taggable rescue nil
  - else
    .alert.alert-info
      Nothing is marked with selected tag.